import type {
  AIBriefing,
  Cost,
  FinanceSettings,
  Investor,
  OutreachLead,
  OutreachMessage,
  Task,
  WeeklyPlan,
} from "./types";

const now = new Date().toISOString();
const today = new Date();
const isoDate = (offsetDays = 0) => {
  const value = new Date(today);
  value.setDate(value.getDate() + offsetDays);
  return value.toISOString().slice(0, 10);
};

export const meritContext = {
  company: "Merit",
  description:
    "Merit is a proof-of-ability platform for early talent. Students showcase real projects, evidence, outcomes, skills, and work history. Recruiters use Merit to evaluate candidates beyond traditional resumes.",
  currentStage: "MVP with early users, recruiter validation, and active product development.",
  coreProblem:
    "Resumes are weak signals for early talent. Students struggle to prove what they can actually do, and recruiters struggle to evaluate ability quickly.",
  coreSolution: "Merit turns student work into structured, shareable, recruiter-readable proof.",
  strategicFocus:
    "Grow student project supply, validate recruiter demand, improve portfolio UI, build recruiter discovery workflow, prepare investor narrative.",
};

export const seedOutreachLeads: OutreachLead[] = [
  {
    id: "lead-1",
    first_name: "Sarah",
    last_name: "Chen",
    linkedin_url: "https://linkedin.com/in/sample-sarah-chen",
    company_name: "TechCorp",
    role_title: "Head of Talent",
    industry: "tech",
    location: "Singapore",
    lead_type: "recruiter",
    source: "Founder referral",
    priority_score: 95,
    personalization_notes: "Scaling graduate engineering hiring and cares about practical project evidence.",
    profile_summary: "Talent leader responsible for early career hiring across engineering and product.",
    pain_angle: "Resume screening creates weak signal for junior roles.",
    merit_angle: "Structured project evidence can shorten screening and improve candidate signal.",
    status: "connected",
    owner: "Founder",
    last_contacted_at: isoDate(-2),
    next_follow_up_at: isoDate(0),
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "lead-2",
    first_name: "Jamie",
    last_name: "Rodriguez",
    linkedin_url: "https://linkedin.com/in/sample-jamie-rodriguez",
    company_name: "FinanceHub",
    role_title: "Recruiter",
    industry: "fintech",
    location: "Singapore",
    lead_type: "recruiter",
    source: "Campus hiring event",
    priority_score: 82,
    personalization_notes: "Hiring interns for data and software roles.",
    profile_summary: "Recruiter focused on internship and graduate roles.",
    pain_angle: "Needs better evidence than resumes for intern screening.",
    merit_angle: "Merit surfaces real student projects and outcomes.",
    status: "message_generated",
    owner: "Growth",
    next_follow_up_at: isoDate(1),
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "lead-3",
    first_name: "Alex",
    last_name: "Park",
    linkedin_url: "https://linkedin.com/in/sample-alex-park",
    company_name: "StartupX",
    role_title: "Co-founder",
    industry: "startup",
    location: "Singapore",
    lead_type: "founder",
    source: "Warm intro",
    priority_score: 88,
    personalization_notes: "Often hires interns and junior operators.",
    profile_summary: "Founder building a B2B SaaS team in Singapore.",
    pain_angle: "Needs high-signal junior candidates without a large recruiting team.",
    merit_angle: "Merit can help identify students with proof of execution.",
    status: "replied",
    owner: "Founder",
    last_contacted_at: isoDate(-5),
    next_follow_up_at: isoDate(0),
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "lead-4",
    first_name: "Priya",
    last_name: "Nair",
    linkedin_url: "https://linkedin.com/in/sample-priya-nair",
    company_name: "NUS Enterprise",
    role_title: "Program Manager",
    industry: "education",
    location: "Singapore",
    lead_type: "school partner",
    source: "School network",
    priority_score: 76,
    personalization_notes: "Runs student startup and internship programs.",
    profile_summary: "Program lead connecting students with startup opportunities.",
    pain_angle: "Students need better proof of their project work.",
    merit_angle: "Merit can make student outcomes visible to recruiters.",
    status: "new",
    owner: "Partnerships",
    next_follow_up_at: isoDate(2),
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "lead-5",
    first_name: "Morgan",
    last_name: "Lee",
    linkedin_url: "https://linkedin.com/in/sample-morgan-lee",
    company_name: "Independent",
    role_title: "Operator Angel",
    industry: "future of work",
    location: "Singapore",
    lead_type: "investor",
    source: "Accelerator office hours",
    priority_score: 90,
    personalization_notes: "Invests in early talent and future-of-work companies.",
    profile_summary: "Operator angel with HR tech and marketplace experience.",
    pain_angle: "Looks for clear wedge and recruiter demand evidence.",
    merit_angle: "Proof-of-ability infrastructure for early talent.",
    status: "meeting_booked",
    owner: "Founder",
    last_contacted_at: isoDate(-1),
    next_follow_up_at: isoDate(3),
    created_at: now,
    updated_at: now,
    created_by: "",
  },
];

export const seedOutreachMessages: OutreachMessage[] = seedOutreachLeads.slice(0, 3).flatMap((lead) => [
  {
    id: `msg-${lead.id}-connection`,
    lead_id: lead.id,
    message_type: "connection_request",
    message_text: `Hi ${lead.first_name}, I noticed your work around ${lead.role_title.toLowerCase()} at ${lead.company_name}. I am building Merit to help teams evaluate early talent through real projects instead of only resumes. Would be useful to connect.`,
    status: "ready",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
]);

export const seedInvestors: Investor[] = [
  {
    id: "investor-1",
    investor_name: "Sarah Johnson",
    firm_name: "Accel",
    investor_type: "VC",
    linkedin_url: "https://linkedin.com/in/sample-sarah-johnson",
    website_url: "https://www.accel.com",
    email: "sample@accel.com",
    location: "Singapore",
    thesis: "Future of work, education, HR tech, and SaaS infrastructure.",
    relevant_portfolio_companies: "WorkOS, Guild, sample HR tech investments",
    check_size_min: 500000,
    check_size_max: 3000000,
    stage_focus: "Seed",
    sector_focus: "future of work",
    warm_intro_source: "Founder network",
    priority_score: 95,
    status: "meeting_booked",
    last_contacted_at: isoDate(-2),
    next_follow_up_at: isoDate(2),
    meeting_date: isoDate(1),
    notes: "Strong thesis fit. Keep pitch focused on recruiter demand and proof-of-ability infrastructure.",
    concerns: "May challenge defensibility and distribution.",
    next_steps: "Prepare meeting brief and ask for recruiter portfolio feedback.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "investor-2",
    investor_name: "James Lee",
    firm_name: "Monk's Hill Ventures",
    investor_type: "VC",
    linkedin_url: "https://linkedin.com/in/sample-james-lee",
    website_url: "https://www.monkshill.com",
    email: "sample@monkshill.com",
    location: "Singapore",
    thesis: "Southeast Asia B2B software and marketplaces.",
    relevant_portfolio_companies: "Regional SaaS and marketplace companies",
    check_size_min: 250000,
    check_size_max: 2000000,
    stage_focus: "Pre-seed / Seed",
    sector_focus: "SaaS",
    warm_intro_source: "Accelerator mentor",
    priority_score: 88,
    status: "researched",
    next_follow_up_at: isoDate(0),
    notes: "Good regional fit; needs clear wedge in Singapore.",
    concerns: "Market size and go-to-market repeatability.",
    next_steps: "Send concise investor note after recruiter pilot data is ready.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "investor-3",
    investor_name: "Anita Rao",
    firm_name: "Future Talent Fund",
    investor_type: "operator angel",
    linkedin_url: "https://linkedin.com/in/sample-anita-rao",
    location: "Singapore",
    thesis: "Education-to-work transition, HR tech, and student mobility.",
    relevant_portfolio_companies: "Career discovery and upskilling startups",
    check_size_min: 25000,
    check_size_max: 150000,
    stage_focus: "Angel",
    sector_focus: "HR tech",
    priority_score: 91,
    status: "contacted",
    last_contacted_at: isoDate(-4),
    next_follow_up_at: isoDate(0),
    notes: "Likely useful as angel plus advisor.",
    concerns: "Wants evidence that recruiters will change workflow.",
    next_steps: "Follow up with recruiter validation summary.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "investor-4",
    investor_name: "Daniel Tan",
    firm_name: "Entrepreneur First",
    investor_type: "accelerator",
    website_url: "https://www.joinef.com",
    email: "sample@joinef.com",
    location: "Singapore",
    thesis: "Pre-seed technical founders and new category creation.",
    relevant_portfolio_companies: "Talent, AI, and marketplace startups",
    check_size_min: 100000,
    check_size_max: 250000,
    stage_focus: "Pre-seed",
    sector_focus: "AI",
    warm_intro_source: "Program alumni",
    priority_score: 84,
    status: "warm_intro_needed",
    next_follow_up_at: isoDate(4),
    notes: "Potential accelerator route and investor network access.",
    concerns: "Needs stronger evidence of founder-market insight.",
    next_steps: "Ask alumni for intro.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
  {
    id: "investor-5",
    investor_name: "Mei Wong",
    firm_name: "SEA Angels",
    investor_type: "angel",
    linkedin_url: "https://linkedin.com/in/sample-mei-wong",
    location: "Southeast Asia",
    thesis: "Student outcomes, marketplace liquidity, and future of work.",
    relevant_portfolio_companies: "Education marketplace and hiring tools",
    check_size_min: 10000,
    check_size_max: 75000,
    stage_focus: "Angel",
    sector_focus: "education",
    priority_score: 80,
    status: "target",
    next_follow_up_at: isoDate(5),
    notes: "Good for first checks and ecosystem intros.",
    concerns: "May need clearer monetization path.",
    next_steps: "Research recent investments and tailor outreach.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
];

export const seedCosts: Cost[] = [
  { id: "cost-1", vendor: "Supabase", category: "hosting", amount: 250, currency: "USD", billing_frequency: "monthly", start_date: isoDate(-90), payment_method: "card", owner: "Engineering", is_recurring: true, notes: "Database and storage", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-2", vendor: "Vercel", category: "hosting", amount: 150, currency: "USD", billing_frequency: "monthly", start_date: isoDate(-90), payment_method: "card", owner: "Engineering", is_recurring: true, notes: "App hosting", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-3", vendor: "OpenAI API", category: "AI/API", amount: 500, currency: "USD", billing_frequency: "monthly", start_date: isoDate(-60), payment_method: "card", owner: "Product", is_recurring: true, notes: "Draft generation and briefings", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-4", vendor: "Domain", category: "software", amount: 50, currency: "USD", billing_frequency: "annual", start_date: isoDate(-120), payment_method: "card", owner: "Founder", is_recurring: true, notes: "Merit domain renewal", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-5", vendor: "Figma", category: "design", amount: 80, currency: "USD", billing_frequency: "monthly", start_date: isoDate(-90), payment_method: "card", owner: "Design", is_recurring: true, notes: "Design workspace", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-6", vendor: "Linear", category: "software", amount: 50, currency: "USD", billing_frequency: "monthly", start_date: isoDate(-90), payment_method: "card", owner: "Product", is_recurring: true, notes: "Execution tracking", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-7", vendor: "Design Contractor", category: "contractor", amount: 3000, currency: "USD", billing_frequency: "one-time", start_date: isoDate(-20), payment_method: "bank transfer", owner: "Founder", is_recurring: false, notes: "Portfolio UI sprint", created_at: now, updated_at: now, created_by: "" },
  { id: "cost-8", vendor: "Recruiter Event", category: "events", amount: 650, currency: "USD", billing_frequency: "one-time", start_date: isoDate(-10), payment_method: "card", owner: "Growth", is_recurring: false, notes: "Founder dinner and recruiter interviews", created_at: now, updated_at: now, created_by: "" },
];

export const seedFinanceSettings: FinanceSettings = {
  id: "finance-1",
  current_cash_balance: 68000,
  monthly_revenue: 2000,
  expected_monthly_revenue: 5000,
  target_monthly_budget: 10000,
  currency: "USD",
  created_at: now,
  updated_at: now,
  created_by: "",
};

export const seedWeeklyPlans: WeeklyPlan[] = [
  {
    id: "week-1",
    week_start_date: isoDate(0),
    weekly_theme: "Recruiter Validation Sprint",
    top_3_priorities:
      "Complete portfolio verification feature\nComplete 5 recruiter validation calls\nPrepare Series Seed pitch deck",
    owner: "Founder",
    status: "in_progress",
    key_metric_target: "Recruiter activation rate: target 40%",
    actual_result: "",
    notes: "Keep the week narrow: recruiter validation, investor prep, and verification unblock.",
    created_at: now,
    updated_at: now,
    created_by: "",
  },
];

export const seedTasks: Task[] = [
  { id: "task-1", title: "Build recruiter messaging templates", description: "Create reusable outreach copy for recruiter segments.", owner: "Product", priority: "low", status: "backlog", due_date: isoDate(7), linked_strategy_pillar: "Recruiter demand", created_at: now, updated_at: now, created_by: "" },
  { id: "task-2", title: "Design analytics dashboard", description: "Define recruiter validation metrics.", owner: "Design", priority: "medium", status: "backlog", due_date: isoDate(10), linked_strategy_pillar: "Portfolio UI", created_at: now, updated_at: now, created_by: "" },
  { id: "task-3", title: "Finalize portfolio UI flow", description: "Finish project evidence and outcome sections.", owner: "Product", priority: "high", status: "this_week", due_date: isoDate(2), linked_strategy_pillar: "Portfolio UI", created_at: now, updated_at: now, created_by: "" },
  { id: "task-4", title: "Complete 5 recruiter validation calls", description: "Ask about screening workflow and willingness to pilot.", owner: "Growth", priority: "critical", status: "this_week", due_date: isoDate(4), linked_strategy_pillar: "Recruiter demand", created_at: now, updated_at: now, created_by: "" },
  { id: "task-5", title: "Prepare investor data room", description: "Collect metrics, pitch narrative, and pilot notes.", owner: "Finance", priority: "high", status: "this_week", due_date: isoDate(5), linked_strategy_pillar: "Fundraising", created_at: now, updated_at: now, created_by: "" },
  { id: "task-6", title: "Implement project verification", description: "Add evidence checks and recruiter-readable verification state.", owner: "Engineering", priority: "high", status: "in_progress", due_date: isoDate(3), linked_strategy_pillar: "Proof of ability", created_at: now, updated_at: now, created_by: "" },
  { id: "task-7", title: "Recruiter onboarding copy", description: "Tighten copy around proof-of-ability evaluation.", owner: "Marketing", priority: "medium", status: "in_progress", due_date: isoDate(2), linked_strategy_pillar: "Recruiter workflow", created_at: now, updated_at: now, created_by: "" },
  { id: "task-8", title: "Deploy new student upload flow", description: "Blocked until storage setup is confirmed.", owner: "Engineering", priority: "critical", status: "blocked", due_date: isoDate(1), linked_strategy_pillar: "Student supply", created_at: now, updated_at: now, created_by: "" },
  { id: "task-9", title: "Student signup flow redesign", description: "Ship simpler onboarding.", owner: "Product", priority: "high", status: "done", due_date: isoDate(-2), linked_strategy_pillar: "Student supply", created_at: now, updated_at: now, created_by: "" },
  { id: "task-10", title: "Pilot pricing review", description: "Review current pilot pricing and budget sensitivity.", owner: "Finance", priority: "medium", status: "done", due_date: isoDate(-1), linked_strategy_pillar: "Revenue", created_at: now, updated_at: now, created_by: "" },
];

export const seedBriefings: AIBriefing[] = [
  {
    id: "briefing-1",
    briefing_type: "daily_founder",
    briefing_text:
      "Top actions: follow up with Sarah Chen, prepare the Accel meeting brief, and unblock project verification. Finance is stable, but API cost needs monitoring.",
    related_data: {},
    created_at: now,
    created_by: "",
  },
  {
    id: "briefing-2",
    briefing_type: "weekly_strategy",
    briefing_text:
      "Execution review: recruiter validation moved, verification is still the constraint, and accelerator outreach should stay deprioritized until the core pilot workflow is stronger.",
    related_data: {},
    created_at: now,
    created_by: "",
  },
];
